config/routes.rb
Rails.application.routes.draw do
  get 'capivaras' => 'welcome#index'
  get 'capivara/:id' => 'welcome#show', as: :capivara_show

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, :idade, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users =  User.all.order(id: 'desc')
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(users_params)

  	if @user.save
  		redirect_to users_path
  	else
  		render :new
  	end
  end

  private

  def users_params
  	params.require(:user).permit(:name, :idade)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@users =  User.where('idade < 30').order(idade: 'desc')
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<h1><%= link_to 'novo user', new_user_path %></h1>

<% @users.each do |user| %>
	<h1><%= user.name %> <%= user.idade %></h1>
	<%= link_to 'ver perfil', user_path(user.id) %>
	<br>
<% end %>

app/views/users/new.html.erb
<h1>Novo User</h1>

<% unless @user.errors.full_messages.empty? %>
	<% @user.errors.full_messages.each do |er| %>
		<h5><%= er %></h5>
	<% end %>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :idade %>
  <%= f.text_field :idade %>
  <br />
  <%= f.submit %>
<% end %>

<br>

<%= link_to 'voltar para index', users_path %>

app/views/users/show.html.erb
<h1>Show</h1>
<br>
<h1><%= @user.name %></h1>
<h1><%= @user.idade %></h1>
<br>
<%= link_to 'voltar para index', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<% @users.each do |user| %>
	<h1><%= user.name %> <%= user.idade %></h1>
	<%= link_to 'ver perfil', capivara_show_path(user.id) %>
	<br>
<% end %>

app/views/welcome/show.html.erb
<h1>Show</h1>
<br>
<h1><%= @user.name %></h1>
<h1><%= @user.idade %></h1>